@base_url = http://localhost:3333
@token = {{login.response.body.token}}

GET {{base_url}}/health

###
# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "username": "testuser"
}

### Get User
GET {{base_url}}/auth/user
Authorization: Bearer {{token}}

### Create BUY Order
POST {{base_url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "BUY",
  "amount": 0.25,
  "price": 45000
}

### Create SELL Order
POST {{base_url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "SELL",
  "amount": 0.1,
  "price": 55000
}

### Cancel Order
DELETE {{base_url}}/orders/1f1bdaab-7033-496d-9eda-3d8b2f99330f
Authorization: Bearer {{token}}

### Get Active Orders
GET {{base_url}}/orders
Authorization: Bearer {{token}}

### Get Matches
GET {{base_url}}/matches
Authorization: Bearer {{token}}

### Get My Matches
GET {{base_url}}/matches/my-matches
Authorization: Bearer {{token}}

### Get Order Book
GET {{base_url}}/order-book
Authorization: Bearer {{token}}
