version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: wisiex_postgres
    restart: always
    environment:
      POSTGRES_USER: wisiex_user
      POSTGRES_PASSWORD: wisiex_pass
      POSTGRES_DB: wisiex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: wisiex_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
