version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wisiex_app
    restart: always
    ports:
      - "3333:3333"
      - "3334:3334"
    environment:
      - PORT=3333
      - WORKER_PORT=3334
      - DATABASE_URL=postgresql://wisiex_user:wisiex_pass@postgres:5432/wisiex_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: wisiex_postgres
    restart: always
    environment:
      POSTGRES_USER: wisiex_user
      POSTGRES_PASSWORD: wisiex_pass
      POSTGRES_DB: wisiex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: wisiex_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
