version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wisiex_app
    restart: always
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
      - "${WORKER_PORT:-3334}:${WORKER_PORT:-3334}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - WORKER_PORT=${WORKER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      # API REST
      - "traefik.http.routers.wisiex.rule=Host(`api.wisiex.pedrodev.com.br`)"
      - "traefik.http.routers.wisiex.entrypoints=websecure"
      - "traefik.http.routers.wisiex.tls.certresolver=letsencrypt"
      - "traefik.http.services.wisiex.loadbalancer.server.port=3333"

  postgres:
    image: postgres:14
    container_name: wisiex_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: wisiex_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  postgres_data:
